version = 1
SPDX-PackageName = "opendatahub-website"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-website"

[[annotations]]
path = [".github/**", "docker/**", ".gitignore", ".pre-commit-config.yaml", ".mailmap", "CONTRIBUTORS.rst", "src/static/icon/**", "src/static/img/**", "src/themes/odh-fbe/LICENSE.md", "src/themes/odh-fbe/static/images/**", "src/themes/odh-fbe/static/fonts/**", "src/themes/odh-fbe/static/favicon.ico", "src/themes/odh-fbe/images/**", ".vscode/**", "src/content/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/public", "src/themes/odh-fbe/static/css/style.css.old", "src/themes/odh-fbe/static/css/style.css.map.old", "src/themes/odh-fbe/layouts/sitemap.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["src/themes/odh-fbe/static/css/bootstrap-v5.css*", "src/themes/odh-fbe/static/js/bootstrap-v5.bundle.min.js", "src/themes/odh-fbe/static/js/bootstrap-v5.bundle.min.js.map"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Twitter, Inc."
SPDX-License-Identifier = "MIT"
