######################################## BASIC CONFIG
theme = "odh-fbe"
baseURL = "https://opendatahub.testingmachine.eu"
languageCode = "en"
title = "Open Data Hub Südtirol - Alto Adige"

######################################## META
[params]
logo = "img/IDM_OPENDATAHUB_2_BK.svg"
logo_NOI = "img/NOI_1_BK.svg"
web_NOI ="https://noi.bz.it"
favicon = "img/logo-open-data-hub.png"
author = "Open Data Hub Südtirol - Alto Adige"
description = "Open Data Hub is your access point to South Tyrol's relevant data. You and your service providers can use Open Data Hub for all channels of digital communication. The data is updated on a regular basis and easily accessible."
PrivacyUrl ="https://noi.bz.it/en/privacy-cookie-policy"

[taxonomies]
type = "datatype"


######################################## css plugins
[[params.plugins.css]]
URL = "/css/animate.css"

[[params.plugins.css]]
URL = "/css/bootstrap.css"

[[params.plugins.css]]
URL = "/css/style.css"

[[params.plugins.css]]
URL = "/css/table-comparison.css"

[[params.plugins.css]]
URL = "/css/custom.css"

[[params.plugins.css]]
URL = "/css/responsive.css"

[[params.plugins.css]]
URL = "/css/availability.css"

[[params.plugins.css]]
URL = "/css/contact-form.css"

[[params.plugins.css]]
URL =  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"


######################################## js plugins
[[params.plugins.js]]
URL = "/js/jquery.min.js"

[[params.plugins.js]]
URL = "/js/jquery.easing.1.3.js"

[[params.plugins.js]]
URL = "/js/bootstrap.min.js"

[[params.plugins.js]]
URL = "/js/jquery.waypoints.min.js"

[[params.plugins.js]]
URL = "/js/jquery.stellar.min.js"

[[params.plugins.js]]
URL = "/js/main.js"

[[params.plugins.js]]
URL = "/js/table-comparison.js"

[[params.plugins.js]]
URL = "/js/cookie.js"

######################################## MENU
[[menu.main]]
URL = "/"
name = "Project"
weight = 1

[[menu.main]]
URL = "/datasets"
name = "Datasets"
weight = 2

[[menu.main]]
URL = "/services"
name = "Services"
weight = 3

[[menu.main]]
URL = "/events"
name = "Events"
weight = 4

[[menu.main]]
URL = "/community"
name = "Community"
weight = 5

[[menu.footer1]]
URL = "/datasets"
name = "Datasets"

[[menu.footer1]]
URL = "https://webcomponents.opendatahub.bz.it"
name = "Web components"

[[menu.footer2]]
URL = "/community"
name = "Community"

[[menu.footer2]]
URL = "/events"
name = "Events"

[[menu.footer3]]
URL = "/data-sharing/"
name = "Data Sharing"

[[menu.footer3]]
URL = "/data-access/"
name = "Data Access"

[[menu.footer3]]
URL = "/services#app-dev"
name = "Data Visualization"


######################################## FOOTER
[params.footer]
logo = "/img/logo-open-data-hub_white.png"

menu_title_1 = "Data"
menu_title_2 = "Community"
menu_title_3 = "Services"

github = "https://github.com/noi-techpark/"
facebook = "https://www.facebook.com/opendatahub/"
telegram = "https://t.me/OpenDataHub"

copyright = "NOI AG - Via Volta 13/A, I-39100 Bolzano - VAT No.: 02595720216 - Endowment capital 110.740.000 € - [Privacy](#)"
